// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8JT_94oxfB7OLYqtII5F74CyhcEzgc0',
    appId: '1:641305189985:android:314e2d909be9c52f0d5420',
    messagingSenderId: '641305189985',
    projectId: 'tiktok-3c650',
    databaseURL: 'https://tiktok-3c650-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-3c650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3iRiD2uj3rNGp9GikwKdzBxx0usJs97U',
    appId: '1:641305189985:ios:0e519a5d6f90995b0d5420',
    messagingSenderId: '641305189985',
    projectId: 'tiktok-3c650',
    databaseURL: 'https://tiktok-3c650-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-3c650.appspot.com',
    iosClientId: '641305189985-s0n444393f0c69nee7ocge4e4fk17md0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
