// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEJ9TzxtxyBlugpFyYEXakGWEbPQWxQ-Q',
    appId: '1:845536969093:web:be6749b83f86055fce04ec',
    messagingSenderId: '845536969093',
    projectId: 'tiktok-a13b2',
    authDomain: 'tiktok-a13b2.firebaseapp.com',
    storageBucket: 'tiktok-a13b2.appspot.com',
    measurementId: 'G-YK6FXFSG9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_CcXKtzm90kcdGnrUVwKQ1ssc-JVV1I',
    appId: '1:845536969093:android:4956be0619b0f487ce04ec',
    messagingSenderId: '845536969093',
    projectId: 'tiktok-a13b2',
    storageBucket: 'tiktok-a13b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4dqyc64lyFewANsy8QHp6fTA-cjdCeg',
    appId: '1:845536969093:ios:a82dc6c476ebbc86ce04ec',
    messagingSenderId: '845536969093',
    projectId: 'tiktok-a13b2',
    storageBucket: 'tiktok-a13b2.appspot.com',
    iosClientId: '845536969093-4q3rrv623qor4pbn9a1u2tv016og3b79.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
